version: "3.9"

services:
  api:
    build:
      context: .
#    image: bekabeka/hw26:latest
    ports:
      - 80:80
#    volumes:
#      - ./docker_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy

#      migrations:
#        condition: service_completed_successfully
#
#
#  migrations:
#    build:
#      context: .
#    image: bekabeka/hw26
#    volumes:
#      - ./docker_config.py:/code/default_config.py
#    depends_on:
#      pg:
#        condition: service_healthy
#    command: flask db upgrade



  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: flask_app
    volumes:
      - ./pg_data2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

